In [1]:
import numpy as np
np.__version__

'1.20.2'

In [ ]:
""" PART 1: Creating arrays"""

In [5]:
# integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [6]:
# float array:
np.array([1, 2, 3, 4], dtype='float32') # or dtype=np.float32

array([1., 2., 3., 4.], dtype=float32)

In [7]:
# nested lists result in multidimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [10]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
# Create a 3x5 floating-point array filled with 1s
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [13]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.76619303, 0.38692413, 0.92285539],
       [0.1110869 , 0.16677142, 0.87536642],
       [0.80533865, 0.73920019, 0.16429804]])

In [21]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 0.3708419 , -0.39235684, -1.29552356],
       [ 0.13208728, -1.02597011,  0.05073203],
       [-1.14120127, -1.42053432,  0.5523332 ]])

In [27]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[9, 5, 1],
       [9, 4, 6],
       [6, 0, 5]])

In [28]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that
# memory location
np.empty(3)

array([1., 1., 1.])

In [31]:
"""
PART 2: 
NumPy Array Attributes
"""

In [38]:
import numpy as np
np.random.seed(0) # seed for reproducibility

x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array

In [44]:
x1

array([5, 0, 3, 3, 7, 9])

In [42]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [43]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [33]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [45]:
print("dtype:", x3.dtype)

dtype: int64


In [46]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


In [52]:
""" Indexing of arrays"""
print(x2[2, -1])
print(x3[0][0])
print(x3[0, 0])
print(x3[0, 0, 1])

7
[8 1 5 9 8]
[8 1 5 9 8]
1


In [53]:
""" Array Slicing: Accessing Subarrays"""

print(x3[:])

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [54]:
x3[:, 0]

array([[8, 1, 5, 9, 8],
       [0, 1, 9, 9, 0],
       [4, 9, 8, 1, 1]])

In [56]:
x3[1]

array([[0, 1, 9, 9, 0],
       [4, 7, 3, 2, 7],
       [2, 0, 0, 4, 5],
       [5, 6, 8, 4, 1]])

In [57]:
x3[3] # yes, that's the first dimension

IndexError: index 3 is out of bounds for axis 0 with size 3

In [77]:
x3[0, 0]

array([8, 1, 5, 9, 8])

In [61]:
# Access first column of all inner arrays of x3
x3[:, :, 0]

array([[8, 9, 5, 1],
       [0, 4, 2, 5],
       [4, 7, 7, 9]])

In [67]:
x3[0:4:1, :, 0]

array([[8, 9, 5, 1],
       [0, 4, 2, 5],
       [4, 7, 7, 9]])

In [79]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [93]:
np.linspace(0, 5, 10)[:, np.newaxis]

array([[0.        ],
       [0.55555556],
       [1.11111111],
       [1.66666667],
       [2.22222222],
       [2.77777778],
       [3.33333333],
       [3.88888889],
       [4.44444444],
       [5.        ]])

In [96]:
np.linspace(0, 5, 10)[np.newaxis]

array([[0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
        2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ]])

In [94]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [100]:
"""Fancy Indexing"""

import numpy as np

rand = np.random.RandomState(42) 
x = rand.randint(100, size=10)
print(x)

[51 92 14 71 60 20 82 86 74 74]


In [104]:
x[[1, 2]]

array([92, 14])

In [105]:
X = np.arange(12).reshape((3, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [106]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
X[row, col]

array([ 2,  5, 11])

In [115]:
X[[0, 0], [1, 2]]

array([1, 2])

In [116]:
"""Sorting array"""

def selection_sort(x):
    for i in range(len(x)):
        swap = i + np.argmin(x[i:])
        (x[i], x[swap]) = (x[swap], x[i])
    return x

x = np.array([2, 1, 4, 3, 5])
selection_sort(x)

array([1, 2, 3, 4, 5])

In [139]:
x = np.array([2, 1, 4, 3, 5])
x

array([2, 1, 4, 3, 5])

In [140]:
x[:-1]

array([2, 1, 4, 3])

In [141]:
x[1:]

array([1, 4, 3, 5])

In [143]:
x[:-1] > x[1:] 

array([ True, False,  True, False])

In [148]:
def bogosort(x):
    while np.any(x[:-1] > x[1:]):
        np.random.shuffle(x)
    return x

x = np.array([2, 1, 4, 3, 5])
# x = np.random.randint(1000000, size=10)
bogosort(x)

array([138138, 281927, 285615, 349316, 404709, 558120, 637936, 840511,
       849222, 969397])

In [159]:
X = np.array([[9, 2, 4], [4, 1, 2]])

In [165]:
np.partition(X,0)

array([[2, 9, 4],
       [1, 4, 2]])

In [166]:
X = rand.rand(10, 2)
X

array([[0.86617615, 0.60111501],
       [0.70807258, 0.02058449],
       [0.96990985, 0.83244264],
       [0.21233911, 0.18182497],
       [0.18340451, 0.30424224],
       [0.52475643, 0.43194502],
       [0.29122914, 0.61185289],
       [0.13949386, 0.29214465],
       [0.36636184, 0.45606998],
       [0.78517596, 0.19967378]])

In [167]:
type(X)

numpy.ndarray

In [171]:
 X[:, np.newaxis, :]

array([[[0.86617615, 0.60111501]],

       [[0.70807258, 0.02058449]],

       [[0.96990985, 0.83244264]],

       [[0.21233911, 0.18182497]],

       [[0.18340451, 0.30424224]],

       [[0.52475643, 0.43194502]],

       [[0.29122914, 0.61185289]],

       [[0.13949386, 0.29214465]],

       [[0.36636184, 0.45606998]],

       [[0.78517596, 0.19967378]]])

In [169]:
X[np.newaxis, :, :]

array([[[0.86617615, 0.60111501],
        [0.70807258, 0.02058449],
        [0.96990985, 0.83244264],
        [0.21233911, 0.18182497],
        [0.18340451, 0.30424224],
        [0.52475643, 0.43194502],
        [0.29122914, 0.61185289],
        [0.13949386, 0.29214465],
        [0.36636184, 0.45606998],
        [0.78517596, 0.19967378]]])